# Generated by Django 4.0.4 on 2022-04-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название соц. сети')),
                ('url', models.CharField(max_length=256, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название салона')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=256, verbose_name='Телефон')),
                ('email', models.CharField(max_length=256, verbose_name='email')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_in', models.TimeField(verbose_name='Время начала работы')),
                ('time_out', models.TimeField(verbose_name='Время окончания работы')),
                ('image', models.ImageField(upload_to='salons/', verbose_name='Картинка салона')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.social', verbose_name='Соц сеть')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits_name', models.CharField(max_length=256, verbose_name='Имя мастера')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия мастера')),
                ('rank', models.CharField(choices=[('JR', 'Младший'), ('MD', 'Мастер'), ('TP', 'Топ')], max_length=256, verbose_name='Ранг мастера')),
                ('image', models.ImageField(upload_to='salons/', verbose_name='Картинка мастера')),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salons.salon', verbose_name='Салон')),
            ],
        ),
    ]
