# Generated by Django 4.0.4 on 2022-06-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_alter_salon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(upload_to='templates/salons/images', verbose_name='Картинка салона'),
        ),
    ]
