# Generated by Django 4.0.4 on 2022-06-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_salon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(upload_to='images/salons/', verbose_name='Картинка салона'),
        ),
    ]
