# Generated by Django 4.0.4 on 2022-06-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_salon_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='service',
        ),
    ]
